import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { AI } from "./action"
import "./globals.css"
import StyledComponentsRegistry from "@/lib/registry"
import AuthProvider from "./context"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*@ts-ignore*/}
        <AI>
          <StyledComponentsRegistry>
            <AuthProvider>{children}</AuthProvider>
          </StyledComponentsRegistry>
        </AI>
      </body>
    </html>
  )
}
